-- MacroDeploy / Profile.lua  (generated by /md export)
-- Regenerate by running /md export and pasting over this file.

local ADDON, NS = ...

local P = {}
NS.Profile = P

P.meta = {
}

P.guards = {
    autoApply        = false,
    maxLevel         = 5,
    requireClass     = nil,
    requireEmptyBars = true,
    emptyBarsRatio   = 0.9,
    realmWhitelist   = nil,
    loginDelay       = 3,
}

P.options = {
    overwriteMacros = true,
    overwriteSlots  = false,
    includeSpells   = true,
    includeItems    = true,
    includeBindings = true,
    bindingSet      = 1,
    retryQueue      = true,
    verbosity       = 1,
}

P.macros = {

}

P.actions = {

}

P.bindings = {

}

return P
